version: '3'

services:
  welp-reviews:
    build: samgetlan/kelp-reviews:latest
    depends_on:
      - 'database'
      - 'cache'
    ports:
      - '3003:3003'

  database:
    image: mongo:latest

  cache:
    image: redis:latest